source: app
# To exclude inside app/
exclude:
  - assets/scripts
  - assets/styles
  - assets/graphics/collecticons
baseurl: ''
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Global variables.
title: 'Jekyll starter'
decription: A starting point for Jekyll based websites.
